/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const BudgetRange = IDL.Variant({
  'over500K' : IDL.Null,
  '_400to500K' : IDL.Null,
  '_300to400K' : IDL.Null,
  'under300K' : IDL.Null,
  'unknown' : IDL.Null,
});
export const BuildTimeline = IDL.Variant({
  'within1Year' : IDL.Null,
  'unsure' : IDL.Null,
  'within6Months' : IDL.Null,
  'immediate' : IDL.Null,
});
export const PriorityLead = IDL.Record({
  'interestedLot' : IDL.Text,
  'source' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'budgetRange' : BudgetRange,
  'buildTimeline' : BuildTimeline,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'getLeads' : IDL.Func([], [IDL.Vec(PriorityLead)], ['query']),
  'submitChatLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, BuildTimeline, IDL.Text],
      [],
      [],
    ),
  'submitLead' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        BudgetRange,
        BuildTimeline,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const BudgetRange = IDL.Variant({
    'over500K' : IDL.Null,
    '_400to500K' : IDL.Null,
    '_300to400K' : IDL.Null,
    'under300K' : IDL.Null,
    'unknown' : IDL.Null,
  });
  const BuildTimeline = IDL.Variant({
    'within1Year' : IDL.Null,
    'unsure' : IDL.Null,
    'within6Months' : IDL.Null,
    'immediate' : IDL.Null,
  });
  const PriorityLead = IDL.Record({
    'interestedLot' : IDL.Text,
    'source' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'budgetRange' : BudgetRange,
    'buildTimeline' : BuildTimeline,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'getLeads' : IDL.Func([], [IDL.Vec(PriorityLead)], ['query']),
    'submitChatLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, BuildTimeline, IDL.Text],
        [],
        [],
      ),
    'submitLead' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          BudgetRange,
          BuildTimeline,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };