/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BudgetRange = { 'over500K' : null } |
  { '_400to500K' : null } |
  { '_300to400K' : null } |
  { 'under300K' : null } |
  { 'unknown' : null };
export type BuildTimeline = { 'within1Year' : null } |
  { 'unsure' : null } |
  { 'within6Months' : null } |
  { 'immediate' : null };
export interface PriorityLead {
  'interestedLot' : string,
  'source' : string,
  'fullName' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
  'budgetRange' : BudgetRange,
  'buildTimeline' : BuildTimeline,
}
export type Time = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'getLeads' : ActorMethod<[], Array<PriorityLead>>,
  'submitChatLead' : ActorMethod<
    [string, string, string, BuildTimeline, string],
    undefined
  >,
  'submitLead' : ActorMethod<
    [string, string, string, BudgetRange, BuildTimeline, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];